### ISSUE TITLE
sq.im.ImageContainer.add_img can't add layer with different number of channel

### ISSUE THREAD

**Issue by aandytu** [scverse/squidpy#650] opened 2023-02-23 22:24 UTC
## Description

Working on adding a segmentation mask to an ImageContainer with 50+ channels. when using `add_img` an error regarding unable to align different number of channels is thrown back. Seems to be an error trying to call Xarray. 

Trying to just run the small example on the [tutorial](https://squidpy.readthedocs.io/en/stable/auto_tutorials/tutorial_image_container.html) gives the same results

## Minimal reproducible example

```python
arr = np.ones((100, 100, 3))
arr[40:60, 40:60] = [0, 0.7, 1]

print(arr.shape)
img = sq.im.ImageContainer(arr, layer="img1")
img

arr_seg = np.zeros((100, 100))
arr_seg[40:60, 40:60] = 1

img.add_img(arr_seg, layer="seg1")
img
```

## Traceback

<details>

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [14], in <module>
      1 arr_seg = np.zeros((100, 100))
      2 arr_seg[40:60, 40:60] = 1
----> 4 img.add_img(arr_seg, layer="seg1")
      5 img

File /opt/conda/envs/analysis/lib/python3.8/site-packages/squidpy/im/_container.py:306, in ImageContainer.add_img(self, img, layer, dims, library_id, lazy, chunks, copy, **kwargs)
    304 logg.info(f"{'Overwriting' if layer in self else 'Adding'} image layer `{layer}`")
    305 try:
--> 306     self.data[layer] = res
    307 except ValueError as e:
    308     c_dim = res.dims[-1]

File /opt/conda/envs/analysis/lib/python3.8/site-packages/xarray/core/dataset.py:1471, in Dataset.__setitem__(self, key, value)
   1466     if isinstance(value, Dataset):
   1467         raise TypeError(
   1468             "Cannot assign a Dataset to a single key - only a DataArray or Variable "
   1469             "object can be stored under a single key."
   1470         )
-> 1471     self.update({key: value})
   1473 elif utils.iterable_of_hashable(key):
   1474     keylist = list(key)

File /opt/conda/envs/analysis/lib/python3.8/site-packages/xarray/core/dataset.py:4909, in Dataset.update(self, other)
   4873 def update(self: T_Dataset, other: CoercibleMapping) -> T_Dataset:
   4874     """Update this dataset's variables with those from another dataset.
   4875 
   4876     Just like :py:meth:`dict.update` this is a in-place operation.
   (...)
   4907     Dataset.merge
   4908     """
-> 4909     merge_result = dataset_update_method(self, other)
   4910     return self._replace(inplace=True, **merge_result._asdict())

File /opt/conda/envs/analysis/lib/python3.8/site-packages/xarray/core/merge.py:1104, in dataset_update_method(dataset, other)
   1101             if coord_names:
   1102                 other[key] = value.drop_vars(coord_names)
-> 1104 return merge_core(
   1105     [dataset, other],
   1106     priority_arg=1,
   1107     indexes=dataset.xindexes,
   1108     combine_attrs="override",
   1109 )

File /opt/conda/envs/analysis/lib/python3.8/site-packages/xarray/core/merge.py:752, in merge_core(objects, compat, join, combine_attrs, priority_arg, explicit_coords, indexes, fill_value)
    749 _assert_compat_valid(compat)
    751 coerced = coerce_pandas_values(objects)
--> 752 aligned = deep_align(
    753     coerced, join=join, copy=False, indexes=indexes, fill_value=fill_value
    754 )
    755 collected = collect_variables_and_indexes(aligned, indexes=indexes)
    756 prioritized = _get_priority_vars_and_indexes(aligned, priority_arg, compat=compat)

File /opt/conda/envs/analysis/lib/python3.8/site-packages/xarray/core/alignment.py:827, in deep_align(objects, join, copy, indexes, exclude, raise_on_invalid, fill_value)
    824     else:
    825         out.append(variables)
--> 827 aligned = align(
    828     *targets,
    829     join=join,
    830     copy=copy,
    831     indexes=indexes,
    832     exclude=exclude,
    833     fill_value=fill_value,
    834 )
    836 for position, key, aligned_obj in zip(positions, keys, aligned):
    837     if key is no_key:

File /opt/conda/envs/analysis/lib/python3.8/site-packages/xarray/core/alignment.py:764, in align(join, copy, indexes, exclude, fill_value, *objects)
    568 """
    569 Given any number of Dataset and/or DataArray objects, returns new
    570 objects with aligned indexes and dimension sizes.
   (...)
    754 
    755 """
    756 aligner = Aligner(
    757     objects,
    758     join=join,
   (...)
    762     fill_value=fill_value,
    763 )
--> 764 aligner.align()
    765 return aligner.results

File /opt/conda/envs/analysis/lib/python3.8/site-packages/xarray/core/alignment.py:552, in Aligner.align(self)
    550 self.assert_no_index_conflict()
    551 self.align_indexes()
--> 552 self.assert_unindexed_dim_sizes_equal()
    554 if self.join == "override":
    555     self.override_indexes()

File /opt/conda/envs/analysis/lib/python3.8/site-packages/xarray/core/alignment.py:452, in Aligner.assert_unindexed_dim_sizes_equal(self)
    450     add_err_msg = ""
    451 if len(sizes) > 1:
--> 452     raise ValueError(
    453         f"cannot reindex or align along dimension {dim!r} "
    454         f"because of conflicting dimension sizes: {sizes!r}" + add_err_msg
    455     )

ValueError: cannot reindex or align along dimension 'channels' because of conflicting dimension sizes: {1, 3}
```

</details>

## Version

Squidpy = 1.2.2
Python = 3.8.12
Xarray = 2023.1.0

**Comment by maxvincent24** [comment] 2023-03-03 10:59
Hello, I'm facing the same error with the same package versions

**Comment by LLehner** [comment] 2023-03-10 15:34
Hi @aandytu 
this error should no longer occur with the latest version of Squidpy. Could you maybe install Squidpy from main and see if the code runs as intended?

**Comment by aandytu** [comment] 2023-03-14 21:07
Hi @LLehner,

I can confirm that with the latest version of Squidpy this issue is solved. Is `1.2.3` considered stable now? Also will it be released on `conda-forge`? It would be helpful for maintaining dependency compatibility.

**Comment by michalk8** [comment] 2023-03-15 08:13
> Also will it be released on conda-forge? It would be helpful for maintaining dependency compatibility. I'm asking because it seems like 1.2.3 is a lot more aggressive in package requirements

Thanks for checking this @aandytu and sorry for the late reply! Yesterday I updated the `conda-forge` recipe, `1.2.3` is already up. Hope this solves your issue.

Closing this a completed, feel free to re-open if there are still problems.

**Closed by michalk8** 2023-03-15 08:13 UTC

**Comment by giovp** [comment] 2023-03-15 20:22
> Hi @LLehner,
> 
> I can confirm that with the latest version of Squidpy this issue is solved. Is `1.2.3` considered stable now? Also will it be released on `conda-forge`? It would be helpful for maintaining dependency compatibility. I'm asking because it seems like 1.2.3 is a lot more aggressive in package requirements, and installing it via pip in my conda environment is causing quite a few conflicts.

apologies, we need to cut new release soon and the constraints on package requirements will be lifted. They already are in `main` in case you can/want to install directly from github.
